import {StyleSheet, Platform} from 'react-native';
import {C} from '../../constants';

const dgl = C.measures.dgl;
export const styles = StyleSheet.create({
  audioPlayerView: {
    borderWidth: 0.8,
    borderColor: '#E1E4E8',
    width: '100%',
    alignSelf: 'center',
    borderRadius: 100,
    paddingHorizontal: 15,
    marginBottom: 15,
  },
  actionsContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '90%',
    marginBottom: 10,
  },
  closeBtn: {alignSelf: 'center', marginRight: 10},
  crossLine: {
    position: 'absolute',
    transform: [{rotate: '-60deg'}],
    top: 15,
    left: -1,
    width: 30,
    height: 1,
    borderBottomColor: '#fff',
    borderBottomWidth: 2,
  },
  durationContainer: {flexDirection: 'row', justifyContent: 'space-between'},
  durationText: {marginTop: 5, marginRight: 5},
  messageView: {
    width: '63%',
    marginHorizontal: 10,
    paddingHorizontal: 4,
    borderTopEndRadius: 10,
    borderTopLeftRadius: 10,
    paddingVertical: 5,
    marginVertical: 5,
  },
  messageSendedStyle: {
    backgroundColor: '#C8EAFC',
    alignSelf: 'flex-end',
    borderBottomLeftRadius: 10,
    borderBottomEndRadius: 0,
  },
  messageRecievedStyle: {
    backgroundColor: '#F1F8FF',
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 0,
    borderBottomEndRadius: 10,
  },
  nameText: {
    fontSize: dgl * 0.014,
    fontFamily: C.font.Medium,
    marginBottom: -5,
    marginTop: -2,
    marginLeft: 5,
    width: '100%',
    color: '#199CD9',
    overflow: 'hidden',
  },
  progressBar: {
    marginTop: dgl * 0.005,
  },
  playIcon: {height: 30, width: 30, resizeMode: 'contain'},
  row: {flexDirection: 'row'},
  row1: {flexDirection: 'row', paddingVertical: 5},
  slider2: {width: '95%', zIndex: 1},
  sliderContainer: {
    width: '90%',
  },
  slider: {
    height: 30,
    width: '100%',
    marginLeft: -5,
    alignSelf: 'center',
  },
  timeText: {
    color: '#6A737D',
    fontSize: dgl * 0.014,
    marginLeft: dgl * 0.042,
  },
  timeText2: {
    color: '#6A737D',
    fontSize: dgl * 0.0115,
    fontFamily: C.font.Medium,
    marginTop: -5,
    marginLeft: dgl * 0.045,
  },
  toggleBtn: {marginTop: 5, marginRight: 10},
  visibleComponentStyle: {
    borderWidth: 1,
    borderColor: '#C8EAFC',
    width: '95%',
    borderRadius: 10,
  },
  videoPlayer: {height: 0, width: 0},
  waves: {
    width: '90%',
    marginTop: Platform.OS === 'ios' ? -7 : -12,
    marginBottom: -40,
    marginLeft: 1.5,
  },
});
