import {StyleSheet} from 'react-native';
import {C} from '../../constants';
const dgl = C.measures.dgl;

export const templateStyles = (theme: any) =>
  StyleSheet.create({
    contentContainer: {
      paddingVertical: dgl * 0.017,
    },
    containerOne: {
      flex: 1,
      flexDirection: 'row',
      width: '90%',
      alignSelf: 'center',
      alignItems: 'center',
    },
    radioButton: {
      width: dgl * 0.023,
      height: dgl * 0.023,
      borderRadius: 100,
      borderWidth: 2,
      alignContent: 'center',
      justifyContent: 'center',
      alignItems: 'center',
    },
    circle: {
      width: dgl * 0.012,
      height: dgl * 0.012,
      borderRadius: 100,
      borderWidth: 1,
    },
    templateBody: {
      paddingLeft: dgl * 0.015,
      paddingRight: dgl * 0.05,
      fontSize: dgl * 0.018,
      fontFamily: C.font.Regular,
      color: theme.colors.PRIMARY,
    },
    templateBox: {
      backgroundColor: theme.colors.CHAT_LIST_BG,
      width: '75%',
      alignSelf: 'center',
      padding: 10,
      borderRadius: 8,
      marginTop: 10,
    },
    text: {
      color: theme.colors.PRIMARY,
      fontSize: 14,
      fontFamily: C.font.Regular,
      letterSpacing: -0.5,
    },
    arrow: {marginLeft: 'auto'},
    TemplateContainer: {
      flex: 1,
      backgroundColor: theme.colors.BACKGROUND,
    },
    mainWrap: {
      flexGrow: 1,
      marginTop: dgl * 0.013,
    },
    templatePramsContainer: {
      flex: 1,
      backgroundColor: theme.colors.BACKGROUND,
    },
    wrapper: {
      paddingBottom: dgl * 0.1,
    },
    textBox: {
      width: '82%',
      backgroundColor: theme.colors.CHAT_LIST_BG,
      paddingHorizontal: dgl * 0.013,
      marginTop: dgl * 0.022,
      paddingVertical: dgl * 0.013,
      borderRadius: 8,
      alignSelf: 'center',
      flex: 1,
    },
    templateText: {
      color: theme.colors.PRIMARY,
      fontSize: dgl * 0.0177,
      fontFamily: C.font.Regular,
      letterSpacing: -0.5,
    },
    paramSub: {
      width: '90%',
      alignSelf: 'center',
      paddingBottom: dgl * 0.02,
    },
    broadcastName: {
      width: '90%',
      alignSelf: 'center',
      marginTop: dgl * 0.033,
      marginBottom: dgl * 0.025,
    },
    paramHeader: {
      color: theme.colors.PRIMARY,
      fontSize: dgl * 0.021,
      fontFamily: C.font.SemiBold,
      letterSpacing: -0.5,
      marginTop: dgl * 0.023,
    },
    upload: {
      width: '90%',
      alignSelf: 'center',
      paddingVertical: dgl * 0.02,
      borderWidth: 0.952,
      borderColor: theme.colors.DARK_GRAYISH_BLUE,
      borderStyle: 'dashed',
      alignItems: 'center',
      borderRadius: 3,
      marginBottom: dgl * 0.015,
      marginTop: dgl * 0.03,
    },
    uploadText: {
      color: theme.colors.GRAY_DARK,
      fontSize: dgl * 0.016,
      fontFamily: C.font.Regular,
      paddingHorizontal: dgl * 0.016,
    },
    format: {
      color: theme.colors.DARK_GRAYISH_BLUE,
      fontSize: dgl * 0.014,
      fontFamily: C.font.Regular,
      paddingHorizontal: dgl * 0.016,
      paddingTop: dgl * 0.005,
    },
    doc: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '90%',
      alignSelf: 'center',
      marginBottom: dgl * 0.05,
      backgroundColor: theme.colors.FIELD,
      paddingHorizontal: dgl * 0.011,
      borderRadius: 4,
      marginVertical: dgl * 0.02,
    },
    docName: {
      color: theme.colors.PRIMARY,
    },
    mediaPlayer: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      backgroundColor: 'black',
      justifyContent: 'center',
    },
    toolbar: {
      marginTop: 30,
      backgroundColor: 'white',
      padding: 10,
      borderRadius: 5,
    },
    vedio: {
      flex: 1,
      width: '100%',
      height: dgl * 0.25,
    },
    fullScreenButton: {
      position: 'absolute',
      right: 10,
      bottom: 10,
      width: 50,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'white',
      borderRadius: 25,
    },
    ButtonContainer: {
      width: '40%',
      borderRadius: dgl * 0.03,
      padding: dgl * 0.0025,
      backgroundColor: theme.colors.TEXT_COLOR,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginVertical: dgl * 0.01,
    },
    activityIndicator: {
      position: 'absolute',
      alignSelf: 'center',
      top: dgl * 0.15,
    },
    indicator: {
      padding: dgl * 0.1,
    },
    imageUpload: {
      backgroundColor: 'rgba(0, 0, 0, 0.09)',
      width: dgl * 0.32,
      height: dgl * 0.17,
      alignSelf: 'center',
    },
    image: {
      resizeMode: 'contain',
      width: dgl * 0.3,
      height: dgl * 0.15,
      alignSelf: 'center',
      zIndex: -1,
    },
    containers: {
      position: 'relative',
      width: '100%',
    },
    uploadBtn: {
      paddingVertical: dgl * 0.006,
    },
    download: {
      width: '90%',
      alignSelf: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    downloadButton: {
      width: '28%',
      paddingVertical: 4,

      borderRadius: 100,
      padding: dgl * 0.0025,
      backgroundColor: theme.colors.TEXT_COLOR,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginVertical: dgl * 0.01,
    },
    sampleCsv: {
      width: '65%',
      color: theme.colors.GRAY_DARK,
      fontSize: dgl * 0.014,
      fontFamily: C.font.Regular,
      paddingHorizontal: dgl * 0.016,
      paddingTop: dgl * 0.005,
    },
    textStyle: {
      fontSize: dgl * 0.014,
    },
    uploadContainer: {
      marginLeft: 'auto',
      paddingRight: 20,
      paddingVertical: 5,
    },
    docCont: {flexDirection: 'row'},
    cancel: {
      alignSelf: 'flex-end',
      zindex: 1,
      top: 0,
    },
    formatcsv:{
      color:'red',
      textAlign:'center',
      paddingBottom:10
    }
  });
