/**
 * flags.ts
 * @desc List of contries with flags and dial code.
 * ...
 */

interface Flag {
  name: string;
  dial_code: number;
  code: string;
  flag: string;
  preferred?: boolean;
  label?: string;
}

const flags: Flag[] = [
  {name: 'Afghanistan', dial_code: 93, code: 'AF', flag: '🇦🇫', label: '🇦🇫 +93'},
  {name: 'Albania', dial_code: 355, code: 'AL', flag: '🇦🇱', label: '🇦🇱 +355'},
  {name: 'Algeria', dial_code: 213, code: 'DZ', flag: '🇩🇿', label: '🇩🇿 +213'},
  {
    name: 'AmericanSamoa',
    dial_code: 1684,
    code: 'AS',
    flag: '🇦🇸',
    label: '🇦🇸 +1684',
  },
  {name: 'Andorra', dial_code: 376, code: 'AD', flag: '🇦🇩', label: '🇦🇩 +376'},
  {name: 'Angola', dial_code: 244, code: 'AO', flag: '🇦🇴', label: '🇦🇴 +244'},
  {
    name: 'Anguilla',
    dial_code: 1264,
    code: 'AI',
    flag: '🇦🇮',
    label: '🇦🇮 +1264',
  },
  {
    name: 'Antarctica',
    dial_code: 672,
    code: 'AQ',
    flag: '🇦🇶',
    label: '🇦🇶 +672',
  },
  {
    name: 'Antigua and Barbuda',
    dial_code: 1268,
    code: 'AG',
    flag: '🇦🇬',
    label: '🇦🇬 +1268',
  },
  {name: 'Argentina', dial_code: 54, code: 'AR', flag: '🇦🇷', label: '🇦🇷 +54'},
  {name: 'Armenia', dial_code: 374, code: 'AM', flag: '🇦🇲', label: '🇦🇲 +374'},
  {name: 'Aruba', dial_code: 297, code: 'AW', flag: '🇦🇼', label: '🇦🇼 +297'},
  {
    name: 'Australia',
    dial_code: 61,
    code: 'AU',
    preferred: true,
    flag: '🇦🇺',
    label: '🇦🇺 +61',
  },
  {name: 'Austria', dial_code: 43, code: 'AT', flag: '🇦🇹', label: '🇦🇹 +43'},
  {
    name: 'Azerbaijan',
    dial_code: 994,
    code: 'AZ',
    flag: '🇦🇿',
    label: '🇦🇿 +994',
  },
  {name: 'Bahamas', dial_code: 1242, code: 'BS', flag: '🇧🇸', label: '🇧🇸 +1242'},
  {name: 'Bahrain', dial_code: 973, code: 'BH', flag: '🇧🇭', label: '🇧🇭 +973'},
  {
    name: 'Bangladesh',
    dial_code: 880,
    code: 'BD',
    flag: '🇧🇩',
    label: '🇧🇩 +880',
  },
  {
    name: 'Barbados',
    dial_code: 1246,
    code: 'BB',
    flag: '🇧🇧',
    label: '🇧🇧 +1246',
  },
  {
    name: 'Belarus',
    dial_code: 375,
    code: 'BY',
    flag: '🇧🇾',
    label: '🇧🇾 +375',
  },
  {
    name: 'Belgium',
    dial_code: 32,
    code: 'BE',
    flag: '🇧🇪',
    label: '🇧🇪 +32',
  },
  {
    name: 'Belize',
    dial_code: 501,
    code: 'BZ',
    flag: '🇧🇿',
    label: '🇧🇿 +501',
  },
  {
    name: 'Benin',
    dial_code: 229,
    code: 'BJ',
    flag: '🇧🇯',
    label: '🇧🇯 +229',
  },
  {
    name: 'Bermuda',
    dial_code: 1441,
    code: 'BM',
    flag: '🇧🇲',
    label: '🇧🇲 +1441',
  },
  {
    name: 'Bhutan',
    dial_code: 975,
    code: 'BT',
    flag: '🇧🇹',
    label: '🇧🇹 +975',
  },
  {
    name: 'Bolivia, Plurinational State of',
    dial_code: 591,
    code: 'BO',
    flag: '🇧🇴',
    label: '🇧🇴 +591',
  },
  {
    name: 'Bosnia and Herzegovina',
    dial_code: 387,
    code: 'BA',
    flag: '🇧🇦',
    label: '🇧🇦 +387',
  },
  {
    name: 'Botswana',
    dial_code: 267,
    code: 'BW',
    flag: '🇧🇼',
    label: '🇧🇼 +267',
  },
  {
    name: 'Brazil',
    dial_code: 55,
    code: 'BR',
    flag: '🇧🇷',
    label: '🇧🇷 +55',
  },
  {
    name: 'British Indian Ocean Territory',
    dial_code: 246,
    code: 'IO',
    flag: '🇮🇴',
    label: '🇮🇴 +246',
  },
  {
    name: 'Brunei Darussalam',
    dial_code: 673,
    code: 'BN',
    flag: '🇧🇳',
    label: '🇧🇳 +673',
  },
  {
    name: 'Bulgaria',
    dial_code: 359,
    code: 'BG',
    flag: '🇧🇬',
    label: '🇧🇬 +359',
  },
  {
    name: 'Burkina Faso',
    dial_code: 226,
    code: 'BF',
    flag: '🇧🇫',
    label: '🇧🇫 +226',
  },
  {name: 'Burundi', dial_code: 257, code: 'BI', flag: '🇧🇮', label: '🇧🇮 +257'},
  {name: 'Cambodia', dial_code: 855, code: 'KH', flag: '🇰🇭', label: '🇰🇭 +855'},
  {name: 'Cameroon', dial_code: 237, code: 'CM', flag: '🇨🇲', label: '🇨🇲 +237'},
  {
    name: 'Canada',
    dial_code: 1,
    code: 'CA',
    flag: '🇨🇦',
    label: '🇨🇦 +1',
  },
  {
    name: 'Cape Verde',
    dial_code: 238,
    code: 'CV',
    flag: '🇨🇻',
    label: '🇨🇻 +238',
  },
  {
    name: 'Cayman Islands',
    dial_code: 345,
    code: 'KY',
    flag: '🇰🇾',
    label: '🇰🇾 +345',
  },
  {
    name: 'Central African Republic',
    dial_code: 236,
    code: 'CF',
    flag: '🇨🇫',
    label: '🇨🇫 +236',
  },
  {
    name: 'Chad',
    dial_code: 235,
    code: 'TD',
    flag: '🇹🇩',
    label: '🇹🇩 +235',
  },
  {
    name: 'Chile',
    dial_code: 56,
    code: 'CL',
    flag: '🇨🇱',
    label: '🇨🇱 +56',
  },
  {
    name: 'China',
    dial_code: 86,
    code: 'CN',
    flag: '🇨🇳',
    label: '🇨🇳 +86',
  },
  {
    name: 'Christmas Island',
    dial_code: 61,
    code: 'CX',
    flag: '🇨🇽',
    label: '🇨🇽 +61',
  },
  {
    name: 'Cocos (Keeling) Islands',
    dial_code: 61,
    code: 'CC',
    flag: '🇨🇨',
    label: '🇨🇨 +61',
  },
  {
    name: 'Colombia',
    dial_code: 57,
    code: 'CO',
    flag: '🇨🇴',
    label: '🇨🇴 +57',
  },
  {
    name: 'Comoros',
    dial_code: 269,
    code: 'KM',
    flag: '🇰🇲',
    label: '🇰🇲 +269',
  },
  {
    name: 'Congo',
    dial_code: 242,
    code: 'CG',
    flag: '🇨🇬',
    label: '🇨🇬 +242',
  },
  {
    name: 'Congo, The Democratic Republic of the',
    dial_code: 243,
    code: 'CD',
    flag: '🇨🇩',
    label: '🇨🇩 +243',
  },
  {
    name: 'Cook Islands',
    dial_code: 682,
    code: 'CK',
    flag: '🇨🇰',
    label: '🇨🇰 +682',
  },
  {
    name: 'Costa Rica',
    dial_code: 506,
    code: 'CR',
    flag: '🇨🇷',
    label: '🇨🇷 +506',
  },
  {
    name: "Cote d'Ivoire",
    dial_code: 225,
    code: 'CI',
    flag: '🇨🇮',
    label: '🇨🇮 +225',
  },
  {name: 'Croatia', dial_code: 385, code: 'HR', flag: '🇭🇷'},
  {name: 'Cuba', dial_code: 53, code: 'CU', flag: '🇨🇺'},
  {name: 'Cyprus', dial_code: 357, code: 'CY', flag: '🇨🇾'},
  {name: 'Czech Republic', dial_code: 420, code: 'CZ', flag: '🇨🇿'},
  {name: 'Denmark', dial_code: 45, code: 'DK', flag: '🇩🇰'},
  {name: 'Djibouti', dial_code: 253, code: 'DJ', flag: '🇩🇯'},
  {name: 'Dominica', dial_code: 1767, code: 'DM', flag: '🇩🇲'},
  {name: 'Dominican Republic', dial_code: 1849, code: 'DO', flag: '🇩🇴'},
  {name: 'Ecuador', dial_code: 593, code: 'EC', flag: '🇪🇨'},
  {name: 'Egypt', dial_code: 20, code: 'EG', flag: '🇪🇬'},
  {name: 'El Salvador', dial_code: 503, code: 'SV', flag: '🇸🇻'},
  {name: 'Equatorial Guinea', dial_code: 240, code: 'GQ', flag: '🇬🇶'},
  {name: 'Eritrea', dial_code: 291, code: 'ER', flag: '🇪🇷'},
  {name: 'Estonia', dial_code: 372, code: 'EE', flag: '🇪🇪'},
  {name: 'Ethiopia', dial_code: 251, code: 'ET', flag: '🇪🇹', label: '🇪🇹  +251'},
  {
    name: 'Falkland Islands (Malvinas)',
    dial_code: 500,
    code: 'FK',
    flag: '🇫🇰',
    label: '🇫🇰  +500',
  },
  {
    name: 'Faroe Islands',
    dial_code: 298,
    code: 'FO',
    flag: '🇫🇴',
    label: '🇫🇴  +298',
  },
  {name: 'Fiji', dial_code: 679, code: 'FJ', flag: '🇫🇯', label: '🇫🇯  +679'},
  {name: 'Finland', dial_code: 358, code: 'FI', flag: '🇫🇮', label: '🇫🇮  +358'},
  {name: 'France', dial_code: 33, code: 'FR', flag: '🇫🇷', label: '🇫🇷  +33'},
  {
    name: 'French Guiana',
    dial_code: 594,
    code: 'GF',
    flag: '🇬🇫',
    label: '🇬🇫  +594',
  },
  {
    name: 'French Polynesia',
    dial_code: 689,
    code: 'PF',
    flag: '🇵🇫',
    label: '🇵🇫  +689',
  },
  {name: 'Gabon', dial_code: 241, code: 'GA', flag: '🇬🇦', label: '🇬🇦  +241'},
  {name: 'Gambia', dial_code: 220, code: 'GM', flag: '🇬🇲', label: '🇬🇲  +220'},
  {name: 'Georgia', dial_code: 995, code: 'GE', flag: '🇬🇪', label: '🇬🇪  +995'},
  {name: 'Germany', dial_code: 49, code: 'DE', flag: '🇩🇪', label: '🇩🇪  +49'},
  {name: 'Ghana', dial_code: 233, code: 'GH', flag: '🇬🇭', label: '🇬🇭 +233'},
  {name: 'Gibraltar', dial_code: 350, code: 'GI', flag: '🇬🇮', label: '🇬🇮 +350'},
  {name: 'Greece', dial_code: 30, code: 'GR', flag: '🇬🇷', label: '🇬🇷 +30'},
  {name: 'Greenland', dial_code: 299, code: 'GL', flag: '🇬🇱', label: '🇬🇱 +299'},
  {name: 'Grenada', dial_code: 1473, code: 'GD', flag: '🇬🇩', label: '🇬🇩 +1473'},
  {name: 'Guadeloupe', dial_code: 590, code: 'GP', flag: '🇬🇵'},
  {name: 'Guam', dial_code: 1671, code: 'GU', flag: '🇬🇺'},
  {name: 'Guatemala', dial_code: 502, code: 'GT', flag: '🇬🇹'},
  {name: 'Guernsey', dial_code: 44, code: 'GG', flag: '🇬🇬'},
  {name: 'Guinea', dial_code: 224, code: 'GN', flag: '🇬🇳'},
  {name: 'Guinea-Bissau', dial_code: 245, code: 'GW', flag: '🇬🇼'},
  {name: 'Guyana', dial_code: 592, code: 'GY', flag: '🇬🇾'},
  {name: 'Haiti', dial_code: 509, code: 'HT', flag: '🇭🇹'},
  {
    name: 'Holy See (Vatican City State)',
    dial_code: 379,
    code: 'VA',
    flag: '🇻🇦',
  },
  {name: 'Honduras', dial_code: 504, code: 'HN', flag: '🇭🇳', label: '🇭🇳 +504'},
  {name: 'Hong Kong', dial_code: 852, code: 'HK', flag: '🇭🇰', label: '🇭🇰 +852'},
  {name: 'Hungary', dial_code: 36, code: 'HU', flag: '🇭🇺', label: '🇭🇺 +36'},
  {name: 'Iceland', dial_code: 354, code: 'IS', flag: '🇮🇸', label: '🇮🇸 +354'},
  {
    name: 'India',
    dial_code: 91,
    code: 'IN',
    preferred: true,
    flag: '🇮🇳',
    label: '🇮🇳 +91',
  },
  {name: 'Indonesia', dial_code: 62, code: 'ID', flag: '🇮🇩', label: '🇮🇩 +62'},
  {
    name: 'Iran, Islamic Republic of',
    dial_code: 98,
    code: 'IR',
    flag: '🇮🇷',
    label: '🇮🇷 +98',
  },
  {name: 'Iraq', dial_code: 964, code: 'IQ', flag: '🇮🇶', label: '🇮🇶 +964'},
  {name: 'Ireland', dial_code: 353, code: 'IE', flag: '🇮🇪', label: '🇮🇪 +353'},
  {name: 'Isle of Man', dial_code: 44, code: 'IM', flag: '🇮🇲', label: '🇮🇲 +44'},
  {name: 'Israel', dial_code: 972, code: 'IL', flag: '🇮🇱', label: '🇮🇱 +972'},
  {name: 'Italy', dial_code: 39, code: 'IT', flag: '🇮🇹', label: '🇮🇹 +39'},
  {name: 'Jamaica', dial_code: 1876, code: 'JM', flag: '🇯🇲', label: '🇯🇲 +1876'},
  {name: 'Japan', dial_code: 81, code: 'JP', flag: '🇯🇵', label: '🇯🇵 +81'},
  {name: 'Jersey', dial_code: 44, code: 'JE', flag: '🇯🇪', label: '🇯🇪 +44'},
  {name: 'Jordan', dial_code: 962, code: 'JO', flag: '🇯🇴', label: '🇯🇴 +962'},
  {name: 'Kazakhstan', dial_code: 77, code: 'KZ', flag: '🇰🇿', label: '🇰🇿 +77'},
  {name: 'Kenya', dial_code: 254, code: 'KE', flag: '🇰🇪', label: '🇰🇪 +254'},
  {name: 'Kiribati', dial_code: 686, code: 'KI', flag: '🇰🇮', label: '🇰🇮 +686'},
  {
    name: "Korea, Democratic People's Republic of",
    dial_code: 850,
    code: 'KP',
    flag: '🇰🇵',
    label: '🇰🇵 +850',
  },
  {
    name: 'Korea, Republic of',
    dial_code: 82,
    code: 'KR',
    flag: '🇰🇷',
    label: '🇰🇷 +82',
  },
  {name: 'Kuwait', dial_code: 965, code: 'KW', flag: '🇰🇼', label: '🇰🇼 +965'},
  {
    name: 'Kyrgyzstan',
    dial_code: 996,
    code: 'KG',
    flag: '🇰🇬',
    label: '🇰🇬 +996',
  },
  {
    name: "Lao People's Democratic Republic",
    dial_code: 856,
    code: 'LA',
    flag: '🇱🇦',
    label: '🇱🇦 +856',
  },
  {name: 'Latvia', dial_code: 371, code: 'LV', flag: '🇱🇻', label: '🇱🇻 +371'},
  {name: 'Lebanon', dial_code: 961, code: 'LB', flag: '🇱🇧', label: '🇱🇧 +961'},
  {name: 'Lesotho', dial_code: 266, code: 'LS', flag: '🇱🇸', label: '🇱🇸 +266'},
  {name: 'Liberia', dial_code: 231, code: 'LR', flag: '🇱🇷', label: '🇱🇷 +231'},
  {
    name: 'Libyan Arab Jamahiriya',
    dial_code: 218,
    code: 'LY',
    flag: '🇱🇾',
    label: '🇱🇾 +218',
  },
  {
    name: 'Liechtenstein',
    dial_code: 423,
    code: 'LI',
    flag: '🇱🇮',
    label: '🇱🇮 +423',
  },
  {name: 'Lithuania', dial_code: 370, code: 'LT', flag: '🇱🇹', label: '🇱🇹 +370'},
  {
    name: 'Luxembourg',
    dial_code: 352,
    code: 'LU',
    flag: '🇱🇺',
    label: '🇱🇺 +352',
  },
  {name: 'Macao', dial_code: 853, code: 'MO', flag: '🇲🇴', label: '🇲🇴 +853'},
  {
    name: 'Macedonia, The Former Yugoslav Republic of',
    dial_code: 389,
    code: 'MK',
    flag: '🇲🇰',
    label: '🇲🇰 +389',
  },
  {
    name: 'Madagascar',
    dial_code: 261,
    code: 'MG',
    flag: '🇲🇬',
    label: '🇲🇬 +261',
  },
  {
    name: 'Malawi',
    dial_code: 265,
    code: 'MW',
    flag: '🇲🇼',
    label: '🇲🇼 +265',
  },
  {
    name: 'Malaysia',
    dial_code: 60,
    code: 'MY',
    flag: '🇲🇾',
    label: '🇲🇾 +60',
  },
  {
    name: 'Maldives',
    dial_code: 960,
    code: 'MV',
    flag: '🇲🇻',
    label: '🇲🇻 +960',
  },
  {
    name: 'Mali',
    dial_code: 223,
    code: 'ML',
    flag: '🇲🇱',
    label: '🇲🇱 +223',
  },
  {
    name: 'Malta',
    dial_code: 356,
    code: 'MT',
    flag: '🇲🇹',
    label: '🇲🇹 +356',
  },
  {
    name: 'Marshall Islands',
    dial_code: 692,
    code: 'MH',
    flag: '🇲🇭',
    label: '🇲🇭 +692',
  },
  {
    name: 'Martinique',
    dial_code: 596,
    code: 'MQ',
    flag: '🇲🇶',
    label: '🇲🇶 +596',
  },
  {
    name: 'Mauritania',
    dial_code: 222,
    code: 'MR',
    flag: '🇲🇷',
    label: '🇲🇷 +222',
  },
  {
    name: 'Mauritius',
    dial_code: 230,
    code: 'MU',
    flag: '🇲🇺',
    label: '🇲🇺 +230',
  },
  {
    name: 'Mayotte',
    dial_code: 262,
    code: 'YT',
    flag: '🇾🇹',
    label: '🇾🇹 +262',
  },
  {
    name: 'Mexico',
    dial_code: 52,
    code: 'MX',
    flag: '🇲🇽',
    label: '🇲🇽 +52',
  },
  {
    name: 'Micronesia, Federated States of',
    dial_code: 691,
    code: 'FM',
    flag: '🇫🇲',
    label: '🇫🇲 +691',
  },
  {
    name: 'Moldova, Republic of',
    dial_code: 373,
    code: 'MD',
    flag: '🇲🇩',
    label: '🇲🇩 +373',
  },
  {
    name: 'Monaco',
    dial_code: 377,
    code: 'MC',
    flag: '🇲🇨',
    label: '🇲🇨 +377',
  },
  {
    name: 'Mongolia',
    dial_code: 976,
    code: 'MN',
    flag: '🇲🇳',
    label: '🇲🇳 +976',
  },
  {
    name: 'Montenegro',
    dial_code: 382,
    code: 'ME',
    flag: '🇲🇪',
    label: '🇲🇪 +382',
  },
  {
    name: 'Montserrat',
    dial_code: 1664,
    code: 'MS',
    flag: '🇲🇸',
    label: '🇲🇸 +1664',
  },
  {
    name: 'Morocco',
    dial_code: 212,
    code: 'MA',
    flag: '🇲🇦',
    label: '🇲🇦 +212',
  },
  {
    name: 'Mozambique',
    dial_code: 258,
    code: 'MZ',
    flag: '🇲🇿',
    label: '🇲🇿 +258',
  },
  {
    name: 'Myanmar',
    dial_code: 95,
    code: 'MM',
    flag: '🇲🇲',
    label: '🇲🇲 +95',
  },
  {
    name: 'Namibia',
    dial_code: 264,
    code: 'NA',
    flag: '🇳🇦',
    label: '🇳🇦 +264',
  },
  {
    name: 'Nauru',
    dial_code: 674,
    code: 'NR',
    flag: '🇳🇷',
    label: '🇳🇷 +674',
  },
  {
    name: 'Nepal',
    dial_code: 977,
    code: 'NP',
    flag: '🇳🇵',
    label: '🇳🇵 +977',
  },
  {
    name: 'Netherlands',
    dial_code: 31,
    code: 'NL',
    flag: '🇳🇱',
    label: '🇳🇱 +31',
  },
  {
    name: 'Netherlands Antilles',
    dial_code: 599,
    code: 'AN',
    flag: '🇦🇳',
    label: '🇦🇳 +599',
  },
  {
    name: 'New Caledonia',
    dial_code: 687,
    code: 'NC',
    flag: '🇳🇨',
    label: '🇳🇨 +687',
  },
  {
    name: 'New Zealand',
    dial_code: 64,
    code: 'NZ',
    flag: '🇳🇿',
    label: '🇳🇿 +64',
  },
  {
    name: 'Nicaragua',
    dial_code: 505,
    code: 'NI',
    flag: '🇳🇮',
    label: '🇳🇮 +505',
  },
  {
    name: 'Niger',
    dial_code: 227,
    code: 'NE',
    flag: '🇳🇪',
    label: '🇳🇪 +227',
  },
  {name: 'Nigeria', dial_code: 234, code: 'NG', flag: '🇳🇬', label: '🇳🇬 +234'},
  {name: 'Niue', dial_code: 683, code: 'NU', flag: '🇳🇺', label: '🇳🇺 +683'},
  {
    name: 'Norfolk Island',
    dial_code: 672,
    code: 'NF',
    flag: '🇳🇫',
    label: '🇳🇫 +672',
  },
  {
    name: 'Northern Mariana Islands',
    dial_code: 1670,
    code: 'MP',
    flag: '🇲🇵',
    label: '🇲🇵 +1670',
  },
  {name: 'Norway', dial_code: 47, code: 'NO', flag: '🇳🇴', label: '🇳🇴 +47'},
  {name: 'Oman', dial_code: 968, code: 'OM', flag: '🇴🇲', label: '🇴🇲 +968'},
  {name: 'Pakistan', dial_code: 92, code: 'PK', flag: '🇵🇰', label: '🇵🇰 +92'},
  {name: 'Palau', dial_code: 680, code: 'PW', flag: '🇵🇼', label: '🇵🇼 +680'},
  {
    name: 'Palestinian Territory, Occupied',
    dial_code: 970,
    code: 'PS',
    flag: '🇵🇸',
    label: '🇵🇸 +970',
  },
  {name: 'Panama', dial_code: 507, code: 'PA', flag: '🇵🇦'},
  {
    name: 'Papua New Guinea',
    dial_code: 675,
    code: 'PG',
    flag: '🇵🇬',
    label: '🇵🇬 +675',
  },
  {name: 'Paraguay', dial_code: 595, code: 'PY', flag: '🇵🇾', label: '🇵🇾 +595'},
  {name: 'Peru', dial_code: 51, code: 'PE', flag: '🇵🇪', label: '🇵🇪 +51'},
  {name: 'Philippines', dial_code: 63, code: 'PH', flag: '🇵🇭', label: '🇵🇭 +63'},
  {name: 'Pitcairn', dial_code: 872, code: 'PN', flag: '🇵🇳', label: '🇵🇳 +872'},
  {name: 'Poland', dial_code: 48, code: 'PL', flag: '🇵🇱', label: '🇵🇱 +48'},
  {name: 'Portugal', dial_code: 351, code: 'PT', flag: '🇵🇹', label: '🇵🇹 +351'},
  {
    name: 'Puerto Rico',
    dial_code: 1939,
    code: 'PR',
    flag: '🇵🇷',
    label: '🇵🇷 +1939',
  },
  {name: 'Qatar', dial_code: 974, code: 'QA', flag: '🇶🇦', label: '🇶🇦 +974'},
  {name: 'Romania', dial_code: 40, code: 'RO', flag: '🇷🇴', label: '🇷🇴 +40'},
  {name: 'Russia', dial_code: 7, code: 'RU', flag: '🇷🇺', label: '🇷🇺 +7'},
  {name: 'Rwanda', dial_code: 250, code: 'RW', flag: '🇷🇼', label: '🇷🇼 +250'},
  {name: 'Réunion', dial_code: 262, code: 'RE', flag: '🇷🇪', label: '🇷🇪 +262'},
  {
    name: 'Saint Barthélemy',
    dial_code: 590,
    code: 'BL',
    flag: '🇧🇱',
    label: '🇧🇱 +590',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dial_code: 290,
    code: 'SH',
    flag: '🇸🇭',
    label: '🇸🇭 +290',
  },
  {
    name: 'Saint Kitts and Nevis',
    dial_code: 1869,
    code: 'KN',
    flag: '🇰🇳',
    label: '🇰🇳 +1869',
  },
  {
    name: 'Saint Lucia',
    dial_code: 1758,
    code: 'LC',
    flag: '🇱🇨',
    label: '🇱🇨 +1758',
  },
  {
    name: 'Saint Martin',
    dial_code: 590,
    code: 'MF',
    flag: '🇲🇫',
    label: '🇲🇫 +590',
  },
  {
    name: 'Saint Pierre and Miquelon',
    dial_code: 508,
    code: 'PM',
    flag: '🇵🇲',
    label: '🇵🇲 +508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    dial_code: 1784,
    code: 'VC',
    flag: '🇻🇨',
    label: '🇻🇨 +1784',
  },
  {
    name: 'Samoa',
    dial_code: 685,
    code: 'WS',
    flag: '🇼🇸',
    label: '🇼🇸 +685',
  },
  {
    name: 'San Marino',
    dial_code: 378,
    code: 'SM',
    flag: '🇸🇲',
    label: '🇸🇲 +378',
  },
  {
    name: 'Sao Tome and Principe',
    dial_code: 239,
    code: 'ST',
    flag: '🇸🇹',
    label: '🇸🇹 +239',
  },
  {
    name: 'Saudi Arabia',
    dial_code: 966,
    code: 'SA',
    flag: '🇸🇦',
    label: '🇸🇦 +966',
  },
  {
    name: 'Senegal',
    dial_code: 221,
    code: 'SN',
    flag: '🇸🇳',
    label: '🇸🇳 +221',
  },
  {
    name: 'Serbia',
    dial_code: 381,
    code: 'RS',
    flag: '🇷🇸',
    label: '🇷🇸 +381',
  },
  {
    name: 'Seychelles',
    dial_code: 248,
    code: 'SC',
    flag: '🇸🇨',
    label: '🇸🇨 +248',
  },
  {
    name: 'Sierra Leone',
    dial_code: 232,
    code: 'SL',
    flag: '🇸🇱',
    label: '🇸🇱 +232',
  },
  {
    name: 'Singapore',
    dial_code: 65,
    code: 'SG',
    flag: '🇸🇬',
    label: '🇸🇬 +65',
  },
  {
    name: 'Slovakia',
    dial_code: 421,
    code: 'SK',
    flag: '🇸🇰',
    label: '🇸🇰 +421',
  },
  {
    name: 'Slovenia',
    dial_code: 386,
    code: 'SI',
    flag: '🇸🇮',
    label: '🇸🇮 +386',
  },
  {
    name: 'Solomon Islands',
    dial_code: 677,
    code: 'SB',
    flag: '🇸🇧',
    label: '🇸🇧 +677',
  },
  {
    name: 'Somalia',
    dial_code: 252,
    code: 'SO',
    flag: '🇸🇴',
    label: '🇸🇴 +252',
  },
  {
    name: 'South Africa',
    dial_code: 27,
    code: 'ZA',
    flag: '🇿🇦',
    label: '🇿🇦 +27',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    dial_code: 500,
    code: 'GS',
    flag: '🇬🇸',
    label: '🇬🇸 +500',
  },
  {name: 'Spain', dial_code: 34, code: 'ES', flag: '🇪🇸', label: '🇪🇸 +34'},
  {name: 'Sri Lanka', dial_code: 94, code: 'LK', flag: '🇱🇰', label: '🇱🇰 +94'},
  {name: 'Sudan', dial_code: 249, code: 'SD', flag: '🇸🇩', label: '🇸🇩 +249'},
  {
    name: 'South Sudan',
    dial_code: 211,
    code: 'SS',
    flag: '🇸🇸',
    label: '🇸🇸 +211',
  },
  {name: 'Suriname', dial_code: 597, code: 'SR', flag: '🇸🇷', label: '🇸🇷 +597'},
  {
    name: 'Svalbard and Jan Mayen',
    dial_code: 47,
    code: 'SJ',
    flag: '🇸🇯',
    label: '🇸🇯 +47',
  },
  {name: 'Swaziland', dial_code: 268, code: 'SZ', flag: '🇸🇿', label: '🇸🇿 +268'},
  {name: 'Sweden', dial_code: 46, code: 'SE', flag: '🇸🇪', label: '🇸🇪 +46'},
  {name: 'Switzerland', dial_code: 41, code: 'CH', flag: '🇨🇭', label: '🇨🇭 +41'},
  {
    name: 'Syrian Arab Republic',
    dial_code: 963,
    code: 'SY',
    flag: '🇸🇾',
    label: '🇸🇾 +963',
  },
  {
    name: 'Taiwan, Province of China',
    dial_code: 886,
    code: 'TW',
    flag: '🇹🇼',
    label: '🇹🇼 +886',
  },
  {
    name: 'Tajikistan',
    dial_code: 992,
    code: 'TJ',
    flag: '🇹🇯',
    label: '🇹🇯 +992',
  },
  {
    name: 'Tanzania, United Republic of',
    dial_code: 255,
    code: 'TZ',
    flag: '🇹🇿',
    label: '🇹🇿 +255',
  },
  {
    name: 'Thailand',
    dial_code: 66,
    code: 'TH',
    flag: '🇹🇭',
    label: '🇹🇭 +66',
  },
  {
    name: 'Timor-Leste',
    dial_code: 670,
    code: 'TL',
    flag: '🇹🇱',
    label: '🇹🇱 +670',
  },
  {
    name: 'Togo',
    dial_code: 228,
    code: 'TG',
    flag: '🇹🇬',
    label: '🇹🇬 +228',
  },
  {
    name: 'Tokelau',
    dial_code: 690,
    code: 'TK',
    flag: '🇹🇰',
    label: '🇹🇰 +690',
  },
  {
    name: 'Tonga',
    dial_code: 676,
    code: 'TO',
    flag: '🇹🇴',
    label: '🇹🇴 +676',
  },
  {
    name: 'Trinidad and Tobago',
    dial_code: 1868,
    code: 'TT',
    flag: '🇹🇹',
    label: '🇹🇹 +1868',
  },
  {
    name: 'Tunisia',
    dial_code: 216,
    code: 'TN',
    flag: '🇹🇳',
    label: '🇹🇳 +216',
  },
  {
    name: 'Turkey',
    dial_code: 90,
    code: 'TR',
    flag: '🇹🇷',
    label: '🇹🇷 +90',
  },
  {
    name: 'Turkmenistan',
    dial_code: 993,
    code: 'TM',
    flag: '🇹🇲',
    label: '🇹🇲 +993',
  },
  {
    name: 'Turks and Caicos Islands',
    dial_code: 1649,
    code: 'TC',
    flag: '🇹🇨',
    label: '🇹🇨 +1649',
  },
  {name: 'Tuvalu', dial_code: 688, code: 'TV', flag: '🇹🇻', label: '🇹🇻 +688'},
  {name: 'Uganda', dial_code: 256, code: 'UG', flag: '🇺🇬', label: '🇺🇬 +256'},
  {name: 'Ukraine', dial_code: 380, code: 'UA', flag: '🇺🇦', label: '🇺🇦 +380'},
  {
    name: 'United Arab Emirates',
    dial_code: 971,
    code: 'AE',
    preferred: true,
    flag: '🇦🇪',
    label: '🇦🇪 +971',
  },
  {
    name: 'United Kingdom',
    dial_code: 44,
    code: 'GB',
    preferred: true,
    flag: '🇬🇧',
    label: '🇬🇧 +44',
  },
  {
    name: 'United States',
    dial_code: 1,
    code: 'US',
    preferred: true,
    flag: '🇺🇸',
    label: '🇺🇸 +1',
  },
  {name: 'Uruguay', dial_code: 598, code: 'UY', flag: '🇺🇾', label: '🇺🇾 +598'},
  {
    name: 'Uzbekistan',
    dial_code: 998,
    code: 'UZ',
    flag: '🇺🇿',
    label: '🇺🇿 +998',
  },
  {name: 'Vanuatu', dial_code: 678, code: 'VU', flag: '🇻🇺', label: '🇻🇺 +678'},
  {
    name: 'Venezuela, Bolivarian Republic of',
    dial_code: 58,
    code: 'VE',
    flag: '🇻🇪',
    label: '🇻🇪 +58',
  },
  {name: 'Viet Nam', dial_code: 84, code: 'VN', flag: '🇻🇳', label: '🇻🇳 +84'},
  {
    name: 'Virgin Islands, British',
    dial_code: 1284,
    code: 'VG',
    flag: '🇻🇬',
    label: '🇻🇬 +1284',
  },
  {
    name: 'Virgin Islands, U.S.',
    dial_code: 1340,
    code: 'VI',
    flag: '🇻🇮',
    label: '🇻🇮 +1340',
  },
  {
    name: 'Wallis and Futuna',
    dial_code: 681,
    code: 'WF',
    flag: '🇼🇫',
    label: '🇼🇫 +681',
  },
  {name: 'Yemen', dial_code: 967, code: 'YE', flag: '🇾🇪', label: '🇾🇪 +967'},
  {name: 'Zambia', dial_code: 260, code: 'ZM', flag: '🇿🇲', label: '🇿🇲 +260'},
  {name: 'Zimbabwe', dial_code: 263, code: 'ZW', flag: '🇿🇼', label: '🇿🇼 +263'},
  {
    name: 'Åland Islands',
    dial_code: 358,
    code: 'AX',
    flag: '🇦🇽',
    label: '🇦🇽 +358',
  },
];

export default flags;
