export const SET_AUDIO_PLAYER = 'SET_AUDIO_PLAYER';
export const SET_AUDIO_TRACK = 'SET_AUDIO_FILE';
export const CLOSE_AUDIO_PLAYER = 'CLOSE_AUDIO_PLAYER';
export const SET_PRESENT_SCREEN = 'SET_PRESENT_SCREEN';
