// Auth Actions
export const AGREE_POLICY_ACTION = 'AGREE_POLICY_ACTION';
export const LOGIN_PRECHECK_ACTION = 'LOGIN_PRECHECK_ACTION';
export const SEND_MAIL_OTP_ACTION = 'SEND_MAIL_OTP_ACTION';
export const SEND_MOBILE_OTP_ACTION = 'SEND_MOBILE_OTP_ACTION';
export const VERIFY_MAIL_OTP_ACTION = 'VERIFY_MAIL_OTP_ACTION';
export const VERIFY_MOBILE_OTP_ACTION = 'VERIFY_MOBILE_OTP_ACTION';
export const REFRESH_AUTH_TOKEN_ACTION = 'REFRESH_AUTH_TOKEN_ACTION';
export const OPERATOR_UPDATE_INFO_ACTION = 'OPERATOR_UPDATE_INFO_ACTION';
export const USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION';
