// Chat Actions
export const GET_CHAT_HISTORY_ACTION = 'GET_CHAT_HISTORY_ACTION';
export const GET_GLOBAL_CHAT_HISTORY_ACTION = 'GET_GLOBAL_CHAT_HISTORY_ACTION';
export const ADD_CHAT_HISTORY_ACTION = 'ADD_CHAT_HISTORY_ACTION';
export const UPDATE_CHAT_HISTORY_ACTION = 'UPDATE_CHAT_HISTORY_ACTION';
export const DELETE_CHAT_HISTORY_ACTION = 'DELETE_CHAT_HISTORY_ACTION';

export const SEND_TEXT_MESSAGE_ACTION = 'SEND_TEXT_MESSAGE_ACTION';
export const SEND_GLOBAL_TEXT_MESSAGE_ACTION =
  'SEND_GLOBAL_TEXT_MESSAGE_ACTION';
export const CHANGE_CHAT_STATUS_ACTION = 'CHANGE_CHAT_STATUS_ACTION';

export const CHAT_HISTORY_FILTER_ACTION = 'CHAT_HISTORY_FILTER_ACTION';

export const SEND_MEDIA_MESSAGE = 'SEND_MEDIA_MESSAGE';
export const SEND_MEDIA_MESSAGE_TO_CHAT = 'SEND_MEDIA_MESSAGE_TO_CHAT';
