// Chat Actions
export const GET_CHATLIST_ACTION = 'GET_CHATLIST_ACTION';
export const GET_GLOBAL_CHATLIST_ACTION = 'GET_GLOBAL_CHATLIST_ACTION';
export const ADD_CHATLIST_ACTION = 'UPDATE_CHATLIST_ACTION';
export const UPDATE_CHATLIST_ACTION = 'UPDATE_CHATLIST_ACTION';
export const DELETE_CHATLIST_ACTION = 'DELETE_CHATLIST_ACTION';

export const UPDATE_CHAT_COUNT_ACTION = 'UPDATE_CHAT_COUNT_ACTION';

export const CHATLIST_FILTER_ACTION = 'CHATLIST_FILTER_ACTION';
