// Contact Actions
export const FETCH_CONTACTS_ACTION = 'FETCH_CONTACTS_ACTION';
export const ADD_CONTACT_ACTION = 'ADD_CONTACT_ACTION';
export const UPDATE_CONTACT_FILTER = 'UPDATE_CONTACT_FILTER';
export const DELETE_CONTACT_ACTION = 'DELETE_CONTACT_ACTION';
