export const ADD_ONS_ACTION = 'ADD_ONS_ACTION';
export const FB_LEADS_LIST_ACTION = 'FB_LEADS_LIST_ACTION';
export const LEAD_STATUS_ACTION = 'LEAD_STATUS_ACTION';
export const LEAD_HISTORY_ACTION = 'LEAD_HISTORY_ACTION';
export const LEAD_TYPE_LIST_ACTION = 'LEAD_TYPE_LIST_ACTION';
export const LEAD_DATA_UPDATE_ACTION = 'LEAD_DATA_UPDATE_ACTION';
