// template actions
export const TEMPLATE_LIST_ACTION = 'TEMPLATE_LIST_ACTION';
export const GLOBAL_TEMPLATE_LIST_ACTION = 'GLOBAL_TEMPLATE_LIST_ACTION';
export const TEMPLATE_LIST_FILTER_ACTION = 'TEMPLATE_LIST_FILTER_ACTION';
export const START_NEW_CHAT_ACTION = 'START_NEW_CHAT_ACTION';
