export enum routeEnum {
  REANIMATEDSCREEN = 'reanimatedscreen',
  THEMESCREEN = 'themescreen',
  ENTRYSCREEN = 'entryscreen',
  LOGINSCREEN = 'loginscreen',
  OTPSCREEN = 'otpscreen',
  CHATBOX = 'chatbox',
  PROFILEINFOSCREEN = 'profileinfoscreen',
  TEMPLATESCREEN = 'templatescreen',
  TEMPLATEPARAMSCREEN = 'templateparamscreen',
  LOGGEDSCREENS = 'loggedscreens',
  HOMESCREEN = 'homescreen',
  SETTINGSSCREEN = 'settingsscreen',
  ADDCONTACTSCREEN = 'addcontactscreen',
  SELECTCONTACT = 'selectcontactscreen',
  CONTACTINFOMAINSCREEN = 'contactinfoscreen',
  PROJECTSTACKSCREEN = 'projectstackscren',
  PROJECTSCREEN = 'projectscreen',
  PROJECTSWITCHINGSCREEN = 'projectswitchingscreen',
  NEWCHATSCREEN = 'newchatscreen',
  SELECTPHOTOSCREEN = 'selectPhotoScreen',
  NEWBROADCASTSCREEN = 'newbroadcastscreen',
  BROADCASTLOGSCREEN = 'broadcastlogscreen',

  DRAWERNAVIGATION = 'drawernavigation',
  ADDONSSCREEN = 'addonsscreen',
  FBLEADSSCREEN = 'fbleadsscreen',
  FBLEADSDETAILSSCREEN = 'fbleadsdetailsscreen',
  LEADLOGSCREEN = 'leadlogscreen',
  FBLEADPROFILESCREEN = 'fbleadprofilescreen',

  MEDIALISTSCREEN = 'medialistscreen',
  PARAMETERSCREEN = 'parameterscreen',
  NOTESECTIONSCREEN = 'notesectionscreen',
}
