/**
 * ChatBox.style.ts
 * @module Chat screen styles
 * @desc style to chat screen
 * @author Sajmal NeoITO
 * @version 0.0.1
 * @access public
 * ...
 */
import {Platform, StyleSheet} from 'react-native';
import {C} from '../../constants';
import measures from '../../constants/measures';

const ChatBoxStyle = (theme: any) => {
  const dgl = C.measures.dgl;
  const ChatBoxStyles = StyleSheet.create({
    aligView: {
      alignSelf: 'flex-end',
    },
    alignView2: {
      alignSelf: 'flex-start',
    },
    animatedView: {
      backgroundColor: '#040921',
      flex: 1,
      justifyContent: 'center',
    },
    botIcon: {
      backgroundColor: '#E1E4E8',
      borderRadius: 100,
      marginLeft: 5,
      marginRight: 10,
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    recordTime: {
      textAlign: 'center',
      fontSize: dgl * 0.017,
      color: '#6A737D',
      backgroundColor: '#fff',
      marginLeft: dgl * 0.015,
      fontFamily: C.font.Medium,
    },
    recordRowStyle: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    recordSection: {
      backgroundColor: '#fff',
      paddingVertical: dgl * 0.015,
      paddingHorizontal: dgl * 0.015,
      elevation: 20,
      shadowOffset: {width: 0, height: 2},
    },
    recordView: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderWidth: 0.8,
      borderColor: '#E1E4E8',
      width: '100%',
      alignSelf: 'center',
      borderRadius: 100,
      paddingHorizontal: 15,
      marginBottom: 15,
      paddingVertical: 7,
    },
    borderRadius: {borderRadius: 100},
    borderRadius1: {borderRadius: 20},
    bottom: {bottom: 25},
    uploadIndicator: {
      height: dgl * 0.05,
      width: dgl * 0.05,
      borderRadius: dgl * 0.05,
      position: 'absolute',
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#e6e6e6',
      top: 85,
      zIndex: 1,
    },
    downloadIconIndicator: {
      position: 'absolute',
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      top: 80,
    },
    durationView: {
      position: 'absolute',
      left: 5,
      bottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
    },
    durationTextStyle: {
      color: '#fff',
      marginLeft: 5,
    },
    backgroundImage: {position: 'absolute', height: '100%', width: '100%'},
    container: {
      flex: 1,
      backgroundColor: theme.colors.BACKGROUND,
    },
    clipIcon: {
      marginHorizontal: dgl * 0.002,
      marginBottom: dgl * 0.025,
    },
    captionView: {bottom: 50, position: 'absolute', alignSelf: 'center'},
    textAlign: {textAlign: 'center'},
    closeBtn: {
      backgroundColor: 'grey',
      position: 'absolute',
      top: Platform.OS === 'android' ? 10 : 60,
      left: 10,
      zIndex: 1,
      padding: 4,
      borderRadius: 100,
    },
    paddingTop: {paddingTop: Platform.OS === 'android' ? '17%' : '33%'},
    dateSection: {
      alignSelf: 'center',
      backgroundColor: theme.colors.LIGHT_BG,
      color: theme.colors.GRAY_LIHGT,
      fontFamily: C.font.Regular,
      fontSize: dgl * 0.015 * theme.fontRef,
      padding: dgl * 0.006,
      paddingHorizontal: dgl * 0.015,
      borderRadius: 5,
      marginBottom: 10,
    },
    flexEnd: {alignSelf: 'flex-end'},
    keyboardAvoidView: {
      maxHeight: '95%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    previewDeleteBtn: {
      backgroundColor: 'red',
      alignSelf: 'center',
      padding: 5,
      borderRadius: 100,
      marginRight: 5,
      marginLeft: -5,
    },
    defaultMenuBackgroundSelected: {backgroundColor: theme.colors.LIGHT_BG},
    defaultMenuBackground: {backgroundColor: 'transparent'},
    defaultMenuText: {
      color: theme.colors.MESSAGE_TEXT_COLOR,
      fontFamily: C.font.Medium,
      bottom: 2,
      alignSelf: 'center',
    },
    descriptionText: {
      maxWidth: '95%',
      textAlign: 'center',
      color: theme.colors.GRAY_LIHGT,
      fontSize: dgl * 0.014 * theme.fontRef,
    },
    defaultMenuIcon: {
      flexDirection: 'row',
      alignContent: 'center',
      paddingVertical: 10,
    },
    dp: {
      width: dgl * 0.05,
      height: dgl * 0.05,
      borderRadius: dgl * 0.05,
      marginHorizontal: dgl * 0.007,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.CHAT_LIST_BG,
    },
    dpText: {
      color: theme.colors.TEXT_COLOR,
      fontSize: dgl * 0.024,
      fontFamily: C.font.Bold,
    },
    eventView: {
      maxWidth: '95%',
      alignSelf: 'center',
      backgroundColor: theme.colors.LIGHT_BG,
      marginVertical: dgl * 0.01,
      padding: 5,
      borderRadius: 10,
    },
    headerComponentView: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? dgl * 0.1 : 60,
      width: '30%',
      backgroundColor: 'transparent',
      alignItems: 'center',
      justifyContent: 'center',
      height: 50,
      zIndex: 10,
      alignSelf: 'center',
    },
    sectionDateText: {
      fontFamily: C.font.Medium,
      textAlign: 'center',
      color: theme.colors.GRAY_LIHGT,
      fontSize: dgl * 0.014 * theme.fontRef,
    },
    sectionDateView: {
      zIndex: 10,
      alignSelf: 'center',
      backgroundColor: theme.colors.LIGHT_BG,
      marginVertical: dgl * 0.01,
      padding: 5,
      borderRadius: 10,
    },
    toastView: {
      position: 'absolute',
      bottom: Platform.OS === 'ios' ? dgl * 0.1 : 60,
      width: '60%',
      backgroundColor: 'transparent',
      alignItems: 'center',
      justifyContent: 'center',
      height: 60,
      zIndex: 10,
      alignSelf: 'center',
    },
    top: {top: Platform.OS === 'ios' ? 80 : 40},
    voiceIcon: {
      backgroundColor: '#E9F6EE',
      borderRadius: 100,
      paddingVertical: 12,
      paddingHorizontal: 15,
      marginLeft: 8,
      alignSelf: 'center',
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    wrap: {flexWrap: 'wrap', width: dgl * 0.3},
    flex: {flex: 1},
    gifIcon: {
      marginHorizontal: dgl * 0.016,
      marginBottom: dgl * 0.025,
    },
    inputView: {
      backgroundColor: theme.colors.LIGHT_BG,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: dgl * 0.013,
      marginBottom: dgl * 0.012,
      borderRadius: 30,
      width: '75%',
      minHeight: Platform.OS === 'ios' ? dgl * 0.05 : undefined,
    },
    imageStyle: {width: dgl / 3.6, height: dgl / 4.2, borderRadius: 4},
    imageEnlargeStyle: {
      width: C.measures.windowWidth,
      height: C.measures.windowHeight / 1.5,
    },
    imageView: {
      borderWidth: 5,
      marginHorizontal: 10,
      borderTopEndRadius: 10,
      borderTopLeftRadius: 10,
      // alignItems: 'center',
      // justifyContent: 'center',
      backgroundColor: '#040921',
    },
    imageEnlargeAnimatedStyles: {
      position: 'absolute',
      top: Platform.OS === 'android' ? 10 : measures.barHeight + 10,
      left: 5,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: Platform.OS === 'android' ? '88%' : '85%',
      zIndex: 10,
    },
    imageEnlargeAnimatedStylesWidth: {
      width: Platform.OS === 'android' ? '78%' : '75%',
    },
    justify: {
      justifyContent: 'flex-start',
      paddingHorizontal: dgl * 0.02,
    },
    mediaMenu: {
      marginTop: -dgl * 0.055,
      marginLeft: -dgl * 0.015,
      width: '70%',
      borderRadius: 10,
    },
    mediaOptionView: {
      alignItems: 'center',
      marginTop: 5,
      paddingHorizontal: dgl * 0.01,
    },
    mediaOptionText: {
      color: '#012040',
      fontSize: dgl * 0.015,
      marginVertical: 5,
    },
    messageView: {
      maxWidth: '70%',
      marginHorizontal: 10,
      paddingLeft: 10,
      borderTopEndRadius: 10,
      borderTopLeftRadius: 10,
      padding: 10,
    },
    messageTxt: {
      color: theme.colors.MESSAGE_TEXT_COLOR,
      fontSize: dgl * 0.014 * theme.fontRef,
      fontFamily: C.font.Medium,
    },
    messageStatusView: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 10,
      marginBottom: 2,
    },
    messageStatusText: {
      color: theme.colors.GRAY_LIHGT,
      fontFamily: C.font.Regular,
      fontSize: dgl * 0.0125 * theme.fontRef,
    },
    messageSendedStyle: {
      backgroundColor: '#C8EAFC',
      alignSelf: 'flex-end',
      borderBottomLeftRadius: 10,
      borderBottomEndRadius: 0,
    },
    messageRecievedStyle: {
      backgroundColor: '#F1F8FF',
      alignSelf: 'flex-start',
      borderBottomLeftRadius: 0,
      borderBottomEndRadius: 10,
    },
    menuStyle: {
      width: '50%',
      borderRadius: 10,
      marginTop: dgl * 0.047,
    },
    menuTextStyle: {
      color: theme.colors.MESSAGE_TEXT_COLOR,
      fontFamily: C.font.Medium,
      bottom: 2,
      width: '80%',
    },
    pdfText: {
      color: '#040921',
      width: dgl / 4.5,
      fontSize: dgl * 0.015,
      marginHorizontal: 5,
    },
    pdfView: {
      borderWidth: 5,
      marginHorizontal: 10,
      borderTopEndRadius: 10,
      borderTopLeftRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      minHeight: dgl * 0.07,
    },
    statusMenuStyle: {
      maxWidth: '60%',
      marginRight: 10,
      justifyContent: 'flex-end',
    },
    pressableTextMessageView: {
      paddingTop: 5,
      marginBottom: 5,
    },
    pdfStyle: {
      flex: 1,
      width: C.measures.windowWidth,
      height: C.measures.windowHeight,
    },
    padding: {paddingVertical: 5},
    rowDirection: {flexDirection: 'row', justifyContent: 'space-between'},
    row1: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '47%',
    },
    row2: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      width: '50%',
    },
    inputWidth: {width: '70%', backgroundColor: 'red'},
    borderColorActive: {borderColor: '#199CD9', width: '87%'},
    borderColorInActive: {borderColor: '#D1D5DA', width: '72%'},
    inputMainView: {
      paddingTop: 10,
      width: '100%',
      flexDirection: 'row',
      // alignItems: 'flex-end',
      justifyContent: 'space-between',
      marginBottom: Platform.OS === 'ios' ? 10 : 0,
      maxHeight: '35%',
    },
    inputSection: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Platform.OS === 'android' ? 7 : 30,
      width: '100%',
      // marginLeft: -3,
    },
    textArea: {
      flexDirection: 'row',
      borderWidth: 1,
      paddingLeft: 10,
      minHeight: 50,
      marginLeft: 5,
      width: '70%',
    },
    arrowPadding: {padding: 10},
    inputStyle: {
      fontFamily: C.font.Regular,
      color: theme.colors.GRAY_LIHGT,
      fontSize: dgl * 0.018,
      width: '80%',
      marginLeft: dgl * 0.01,
      borderRadius: 50,
      alignSelf: 'center',
      paddingBottom: 10,
      backgroundColor: '#fff',
    },
    imojiIcon: {
      alignSelf: 'flex-end',
      marginBottom: Platform.OS === 'android' ? 15 : 15,
    },
    zindex1: {zIndex: 10},
    zindex2: {zIndex: 0},
    rowDirection2: {flexDirection: 'row', alignItems: 'center'},
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    row3: {flexDirection: 'row', justifyContent: 'flex-end'},
    senderNameView: {
      marginHorizontal: 10,
      width: '80%',
    },
    senderText: {
      color: '#fff',
      fontFamily: C.font.Medium,
      fontSize: dgl * 0.018,
    },
    rowView: {
      alignItems: 'center',
      backgroundColor: theme.colors.TEXT_COLOR,
      flexDirection: 'row',
      padding: dgl * 0.01,
      paddingTop: Platform.OS === 'ios' ? dgl * 0.05 : dgl * 0.014,
      width: '100%',
      justifyContent: 'space-between',
    },
    sendIcon: {
      marginHorizontal: dgl * 0.007,
      // marginBottom: dgl * 0.01,
    },
    chatDate: {
      color: '#CBDBE2',
      fontFamily: C.font.Regular,
      fontSize: dgl * 0.012,
    },
    forwardView: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 15,
    },
    margin: {marginRight: 15},
    textBackground1: {
      backgroundColor: '#C8EAFC',
      width: dgl / 3.6,
    },
    textBackground2: {
      backgroundColor: '#F1F8FF',
      width: dgl / 3.6,
    },
    imageSendedStyle: {
      borderBottomLeftRadius: 10,
      borderBottomEndRadius: 0,
      alignSelf: 'flex-end',
      borderColor: '#C8EAFC',
    },
    imageRecievedStyle: {
      borderBottomLeftRadius: 0,
      borderBottomEndRadius: 10,
      alignSelf: 'flex-start',
      borderColor: '#F1F8FF',
    },
    pdfSendedStyle: {
      borderBottomLeftRadius: 10,
      borderBottomEndRadius: 0,
      alignSelf: 'flex-end',
      borderColor: '#C8EAFC',
      backgroundColor: '#C8EAFC',
    },
    pdfRecievedStyle: {
      borderBottomLeftRadius: 0,
      borderBottomEndRadius: 10,
      alignSelf: 'flex-start',
      borderColor: '#F1F8FF',
      backgroundColor: '#F1F8FF',
    },
    statusMenuHeader: {
      fontSize: dgl * 0.016,
      paddingVertical: dgl * 0.01,
      fontFamily: C.font.Medium,
      paddingHorizontal: dgl * 0.01,
      color: theme.colors.GRAY_LIHGT,
    },
    defaultBackground: {
      backgroundColor: 'transparent',
    },
    selectedBackground: {
      padding: 10,
    },
    selectedBackgroundColor: {
      backgroundColor: theme.colors.LIGHT_BG,
    },
    statusView: {
      backgroundColor: theme.colors.BACKGROUND,
      marginLeft: dgl * 0.01,
      paddingHorizontal: dgl * 0.016,
      borderRadius: dgl * 0.085,
      maxWidth: '90%',
      paddingVertical: dgl * 0.005,
      height: dgl * 0.042,
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 8,
      marginRight: -dgl * 0.01,
      paddingRight: 20,
    },
    width: {width: '100%'},
    block: {
      backgroundColor: '#fff',
      padding: dgl * 0.01,
      borderRadius: dgl * 0.085,
      justifyContent: 'center',
      alignItems: 'center',
    },
    blockText: {
      fontFamily: C.font.SemiBold,
      fontSize: dgl * 0.015,
    },
    blockText2: {
      fontSize: dgl * 0.013,
      color: 'gray',
    },
    openTextColor: {
      color: theme.colors.STATUS_PRIMARY_COLOR,
    },
    resolvedTextColor: {
      color: theme.colors.STATUS_TEXT_COLOR,
    },
    statusTextOpen: {
      fontSize: dgl * 0.0135,
      color: theme.colors.STATUS_PRIMARY_COLOR,
    },
    statusTextResolved: {
      fontSize: dgl * 0.012,
      color: theme.colors.STATUS_TEXT_COLOR,
    },
    statusMenuOptionText: {
      fontSize: dgl * 0.016,
      fontFamily: C.font.Medium,
      paddingLeft: dgl * 0.025,
      paddingTop: dgl * 0.006,
    },
    statusText: {
      fontFamily: C.font.SemiBold,
      marginRight: dgl * 0.003,
      fontSize: dgl * 0.015,
      maxWidth: '100%',
      minWidth: '30%',
    },
    swipeableIconView: {
      backgroundColor: theme.colors.CHAT_LIST_BG,
      position: 'absolute',
      top: 10,
      padding: 10,
      borderRadius: 100,
    },
    textStyle: {
      color: theme.colors.BACKGROUND,
      fontSize: dgl * 0.02,
      fontFamily: C.font.Medium,
      maxWidth: '70%',
    },
    timer: {
      borderColor: theme.colors.BACKGROUND,
      borderWidth: 1.5,
      borderRadius: dgl * 0.085,
      height: dgl * 0.042,
      minWidth: dgl * 0.08,
    },
    timeText: {
      color: theme.colors.BACKGROUND,
      fontFamily: C.font.SemiBold,
      textAlign: 'center',
      fontSize: dgl * 0.013,
      maxWidth: dgl * 0.06,
      marginLeft: dgl * 0.005,
      top: 2,
    },
    blockBox: {
      borderColor: theme.colors.GRAY_BORDER,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 10,
      borderWidth: 1.5,
      borderRadius: 10,
      backgroundColor: theme.colors.LIGHT_BG,
      width: '95%',
      alignSelf: 'center',
      marginVertical: 10,
    },
    blockHead: {
      fontFamily: C.font.Medium,
      fontSize: dgl * 0.018 * theme.fontRef,
      color: theme.colors.GRAY_LIHGT,
      textAlign: 'justify',
    },
    blockDesc: {
      fontFamily: C.font.Regular,
      fontSize: dgl * 0.016 * theme.fontRef,
      color: theme.colors.GRAY_LIHGT,
      textAlign: 'justify',
    },
    templateBox: {
      marginVertical: 10,
      padding: 7,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.TEXT_COLOR,
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
    },
    templateText: {
      color: theme.colors.TEXT_COLOR,
      fontFamily: C.font.Medium,
      fontSize: dgl * 0.015 * theme.fontRef,
      textAlign: 'center',
    },
    videoStyle: {width: 0, height: 0},
  });
  return {ChatBoxStyles};
};

export default ChatBoxStyle;
